FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x entrypoint.sh

EXPOSE 5000


CMD ["./entrypoint.sh"]

#CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "run:app"]